export const STANDARD_GRID = [
  [
    "AA",
    "AKs",
    "AQs",
    "AJs",
    "ATs",
    "A9s",
    "A8s",
    "A7s",
    "A6s",
    "A5s",
    "A4s",
    "A3s",
    "A2s",
  ],
  [
    "AKo",
    "KK",
    "KQs",
    "KJs",
    "KTs",
    "K9s",
    "K8s",
    "K7s",
    "K6s",
    "K5s",
    "K4s",
    "K3s",
    "K2s",
  ],
  [
    "AQo",
    "KQo",
    "QQ",
    "QJs",
    "QTs",
    "Q9s",
    "Q8s",
    "Q7s",
    "Q6s",
    "Q5s",
    "Q4s",
    "Q3s",
    "Q2s",
  ],
  [
    "AJo",
    "KJo",
    "QJo",
    "JJ",
    "JTs",
    "J9s",
    "J8s",
    "J7s",
    "J6s",
    "J5s",
    "J4s",
    "J3s",
    "J2s",
  ],
  [
    "ATo",
    "KTo",
    "QTo",
    "JTo",
    "TT",
    "T9s",
    "T8s",
    "T7s",
    "T6s",
    "T5s",
    "T4s",
    "T3s",
    "T2s",
  ],
  [
    "A9o",
    "K9o",
    "Q9o",
    "9Jo",
    "9To",
    "99",
    "98s",
    "97s",
    "96s",
    "95s",
    "94s",
    "93s",
    "92s",
  ],
  [
    "A8o",
    "K8o",
    "Q8o",
    "J8o",
    "T8o",
    "98o",
    "88",
    "87s",
    "86s",
    "85s",
    "84s",
    "83s",
    "82s",
  ],
  [
    "A7o",
    "K7o",
    "Q7o",
    "J7o",
    "T7o",
    "97o",
    "87o",
    "77",
    "76s",
    "75s",
    "74s",
    "73s",
    "72s",
  ],
  [
    "A6o",
    "K6o",
    "Q6o",
    "J6o",
    "T6o",
    "96o",
    "86o",
    "76o",
    "66",
    "65s",
    "64s",
    "63s",
    "62s",
  ],
  [
    "A5o",
    "K5o",
    "Q5o",
    "J5o",
    "T5o",
    "95o",
    "85o",
    "75o",
    "65o",
    "55",
    "54s",
    "53s",
    "52s",
  ],
  [
    "A4o",
    "K4o",
    "Q4o",
    "J4o",
    "T4o",
    "94o",
    "84o",
    "74o",
    "64o",
    "54o",
    "44",
    "43s",
    "42s",
  ],
  [
    "A3o",
    "K3o",
    "Q3o",
    "J3o",
    "T3o",
    "93o",
    "83o",
    "73o",
    "63o",
    "53o",
    "43o",
    "33",
    "32s",
  ],
  [
    "A2o",
    "K2o",
    "Q2o",
    "J2o",
    "T2o",
    "92o",
    "82o",
    "72o",
    "62o",
    "52o",
    "42o",
    "32o",
    "22",
  ],
];

export const DEFAULT_VALUES = {
  AA: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  AKs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  AQs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  AJs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  ATs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A9s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A8s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A7s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A6s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A5s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A4s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A3s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A2s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  AKo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  KK: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  KQs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  KJs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  KTs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K9s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K8s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K7s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K6s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K5s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K4s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K3s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K2s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  AQo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  KQo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  QQ: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  QJs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  QTs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q9s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q8s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q7s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q6s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q5s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q4s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q3s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q2s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  AJo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  KJo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  QJo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  JJ: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  JTs: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J9s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J8s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J7s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J6s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J5s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J4s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J3s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J2s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  ATo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  KTo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  QTo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  JTo: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  TT: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T9s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T8s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T7s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T6s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T5s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T4s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T3s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T2s: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A9o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K9o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q9o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "9Jo": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "9To": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "99": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "98s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "97s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "96s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "95s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "94s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "93s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "92s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A8o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K8o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q8o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J8o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T8o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "98o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "88": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "87s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "86s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "85s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "84s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "83s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "82s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A7o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K7o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q7o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J7o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T7o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "97o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "87o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "77": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "76s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "75s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "74s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "73s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "72s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A6o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K6o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q6o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J6o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T6o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "96o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "86o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "76o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "66": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "65s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "64s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "63s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "62s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A5o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K5o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q5o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J5o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T5o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "95o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "85o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "75o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "65o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "55": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "54s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "53s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "52s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A4o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K4o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q4o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J4o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T4o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "94o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "84o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "74o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "64o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "54o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "44": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "43s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "42s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A3o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K3o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q3o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J3o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T3o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "93o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "83o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "73o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "63o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "53o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "43o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "33": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "32s": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  A2o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  K2o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  Q2o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  J2o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  T2o: {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "92o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "82o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "72o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "62o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "52o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "42o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "32o": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
  "22": {
    bb: { colour: "" },
    sb: { colour: "" },
    utg: { colour: "" },
    mp: { colour: "" },
    co: { colour: "" },
    btn: { colour: "" },
  },
};

export const SIX_HAND_POSITIONS = ["SB", "BB", "UTG", "MP", "CO", "BTN"];
